all:
    BUILD +test-help
    BUILD +test-bkup

test-help:
    FROM alpine
    COPY ..+acbup/acbup /bin/.
    RUN acbup --help 2>&1 | grep 'display this help'

test-bkup:
    FROM alpine
    COPY ..+acbup/acbup /bin/.
    RUN echo "src=/root/files" > acbup.conf && \
        echo "dst=/root/bkup" >> acbup.conf

    RUN mkdir /root/files
    RUN echo "alpha" > /root/files/a.txt
    RUN echo "bravo" > /root/files/b.txt
    RUN echo "charlie" > /root/files/c.txt
    RUN echo "delta" > /root/files/d.txt

    RUN mkdir -p /root/files/sub/dir
    RUN echo "echo" > /root/files/sub/dir/e.txt

    RUN acbup --config=acbup.conf

    # bee07a7f6a5e8ae619273e1a143562cbb5468d7c is the contents of the ref entry for the above test /root/files/...
    # if those filenames change, then this hash will need to be updated
    RUN test "$(cat /root/bkup/refs)" = "bee07a7f6a5e8ae619273e1a143562cbb5468d7c"
    RUN ls /root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c
    RUN ls /root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c.bkup
    RUN test "$(cat /root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c | sha1sum - | awk '{print $1}')" = "bee07a7f6a5e8ae619273e1a143562cbb5468d7c"

    RUN acbup --config=acbup.conf
    RUN set -o pipefail && acbup --config=acbup.conf --list | tee output.txt
    RUN test "$(head -n 1 output.txt)" = "/root/files/a.txt"
    RUN test "$(head -n 2 output.txt | tail -n 1)" = "/root/files/b.txt"
    RUN test "$(head -n 3 output.txt | tail -n 1)" = "/root/files/c.txt"
    RUN test "$(head -n 4 output.txt | tail -n 1)" = "/root/files/d.txt"
    RUN test "$(tail -n 1 output.txt)" = "/root/files/sub/dir/e.txt"

    # corrupt the refs metadata with 3 bogus bytes at position 10
    RUN printf '\x31\xc0\xc3' | dd of=/root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c bs=1 seek=10 count=3 conv=notrunc

    RUN set -o pipefail && ((acbup --config=acbup.conf --verify 2>&1 | tee output.txt) || (touch /failed)) && rm /failed
    RUN cat output.txt | grep 'detected corruption in /root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c while reading refs'
    RUN acbup --config=acbup.conf --recover
    # TODO fix the output of --recover to include the ref under numRecovered; currently it will recover a corrupted refs, but it doesn't report it was recovered

    # should still work
    RUN set -o pipefail && acbup --config=acbup.conf --list | tee output.txt
    RUN test "$(head -n 1 output.txt)" = "/root/files/a.txt"
    RUN test "$(head -n 2 output.txt | tail -n 1)" = "/root/files/b.txt"
    RUN test "$(head -n 3 output.txt | tail -n 1)" = "/root/files/c.txt"
    RUN test "$(head -n 4 output.txt | tail -n 1)" = "/root/files/d.txt"
    RUN test "$(tail -n 1 output.txt)" = "/root/files/sub/dir/e.txt"

    # refs should not have changed (since no new files were added)
    RUN test "$(cat /root/bkup/refs)" = "bee07a7f6a5e8ae619273e1a143562cbb5468d7c"

    # mess with bkup and test it gets restored
    RUN printf '\x31\xc0\xc3' | dd of=/root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c.bkup bs=1 seek=10 count=3 conv=notrunc
    RUN acbup --config=acbup.conf
    RUN diff -q /root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c /root/bkup/data/be/e0/7a/bee07a7f6a5e8ae619273e1a143562cbb5468d7c.bkup

    # next corrupt the backed up file
    RUN echo "extra-data" >> /root/bkup/data/d0/46/cd/d046cd9b7ffb7661e449683313d41f6fc33e3130

    RUN set -o pipefail && ((acbup --config=acbup.conf --verify 2>&1 | tee output.txt) || (touch /failed)) && rm /failed
    RUN cat output.txt | grep '/root/bkup/data/d0/46/cd/d046cd9b7ffb7661e449683313d41f6fc33e3130 is corrupt'
    RUN acbup --config=acbup.conf --recover
    RUN test "$(cat /root/bkup/data/d0/46/cd/d046cd9b7ffb7661e449683313d41f6fc33e3130 | sha1sum - | awk '{print $1}')" = "d046cd9b7ffb7661e449683313d41f6fc33e3130"

    # next corrupt the backed up file's bkup
    RUN echo "bad-data" >> /root/bkup/data/d0/46/cd/d046cd9b7ffb7661e449683313d41f6fc33e3130.bkup
    RUN set -o pipefail && ((acbup --config=acbup.conf --verify 2>&1 | tee output.txt) || (touch /failed)) && rm /failed
    RUN cat output.txt | grep '/root/bkup/data/d0/46/cd/d046cd9b7ffb7661e449683313d41f6fc33e3130.bkup is corrupt'
    RUN acbup --config=acbup.conf --recover
    RUN test "$(cat /root/bkup/data/d0/46/cd/d046cd9b7ffb7661e449683313d41f6fc33e3130.bkup | sha1sum - | awk '{print $1}')" = "d046cd9b7ffb7661e449683313d41f6fc33e3130"

    # next change the local copy to test acbup detects the change and prompts the user on what to do.
    RUN echo "aleph" > /root/files/a.txt
    RUN set -o pipefail && ((acbup --config=acbup.conf 2>&1 | tee output.txt) || (touch /failed)) && rm /failed
    RUN cat output.txt | grep 'local copy of /root/files/a.txt has been changed since backup'
