all:
    BUILD +test-help
    BUILD +test-bkup

test-help:
    FROM alpine
    COPY ..+acbup/acbup /bin/.
    RUN acbup --help 2>&1 | grep 'display this help'

test-bkup:
    FROM alpine
    COPY ..+acbup/acbup /bin/.
    RUN echo "src=/root/files" > acbup.conf && \
        echo "dst=/root/bkup" >> acbup.conf

    RUN mkdir /root/files
    RUN echo "alpha" > /root/files/a.txt
    RUN echo "bravo" > /root/files/b.txt
    RUN echo "charlie" > /root/files/c.txt
    RUN echo "delta" > /root/files/d.txt

    RUN mkdir -p /root/files/sub/dir
    RUN echo "echo" > /root/files/sub/dir/e.txt

    RUN acbup --config=acbup.conf
    RUN ls /root/bkup/refs/meta
    RUN ls /root/bkup/refs/meta.sha1
    RUN ls /root/bkup/refs/meta.bkup

    RUN acbup --config=acbup.conf
    RUN set -o pipefail && acbup --config=acbup.conf --list | tee output.txt
    RUN test "$(head -n 1 output.txt)" = "/root/files/a.txt"
    RUN test "$(head -n 2 output.txt | tail -n 1)" = "/root/files/b.txt"
    RUN test "$(head -n 3 output.txt | tail -n 1)" = "/root/files/c.txt"
    RUN test "$(head -n 4 output.txt | tail -n 1)" = "/root/files/d.txt"
    RUN test "$(tail -n 1 output.txt)" = "/root/files/sub/dir/e.txt"

    # corrupt the refs metadata with 3 bogus bytes at position 10
    RUN printf '\x31\xc0\xc3' | dd of=/root/bkup/refs/meta bs=1 seek=10 count=3 conv=notrunc

    # TODO implement these
    # RUN echo acbup --config=acbup.conf --verify
    # RUN echo acbup --config=acbup.conf --recover

    # should still work
    RUN set -o pipefail && acbup --config=acbup.conf --list | tee output.txt
    RUN test "$(head -n 1 output.txt)" = "/root/files/a.txt"
    RUN test "$(head -n 2 output.txt | tail -n 1)" = "/root/files/b.txt"
    RUN test "$(head -n 3 output.txt | tail -n 1)" = "/root/files/c.txt"
    RUN test "$(head -n 4 output.txt | tail -n 1)" = "/root/files/d.txt"
    RUN test "$(tail -n 1 output.txt)" = "/root/files/sub/dir/e.txt"

    # next corrupt the backed up file
    RUN echo "extra-data" >> /root/bkup/data/d0/46/cd/d046cd9b7ffb7661e449683313d41f6fc33e3130
    RUN echo TODO: implement a --verify / --recover mode. Currently we just re-upload the existing local file.
    RUN set -o pipefail && acbup --config=acbup.conf | tee output.txt

    # next change the local copy to test acbup detects the change and prompts the user on what to do.
    RUN echo "aleph" > /root/files/a.txt
    RUN set -o pipefail && ((acbup --config=acbup.conf 2>&1 | tee output.txt) || (touch /failed)) && rm /failed
    RUN cat output.txt | grep 'local copy of /root/files/a.txt has been changed since backup'
